---
name: 'Sync Drupal security updates with JIRA'
description: 'Check a Drupal site corresponding to the current repository for security updates and creates JIRA tickets accordingly.'
author: 'reload'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'rotate-cw'
  color: 'green'
